# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'tcler''s blog'
tagline:             '--- 其实我是一个程序员<br>
Show me your flowcharts and conceal your tables, and I shall continue to be mystified. Show me your tables, and I won’t usually need your flowcharts; they’ll be obvious.'
description:         'tcler''s blog, based on <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme <a href="http://jekyllthemes.io/theme/15489219/lanyon">Lanyon</a>'
url:                 https://tcler.github.io
baseurl:             ''
paginate:            8
gems: [jekyll-paginate]

# About/contact
author:
  name:              Jianhong Yin
  url:               https://github.com/tcler
  email:             yin-jianhong@163.com

# Custom vars
version:             1.0.0
